databases:
  - name: minamo-db
    user: minamo_user
    databaseName: minamo_db
    plan: free
services:
  - name: minamo-editor
    type: web
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn minamo_editor.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minamo-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
